### ISSUE TITLE
20200121当日进展-zzy

### ISSUE THREAD

**Issue by jerryzuo0214** [jerryzuo0214/Integrated_Examination_Of_Ten_Subjects_WMU#2]
定义了数据库架构规范，进行了分工，分别开始数据库的建立

**Comment by yy-skr** [comment]
[虞嫣-20210121.xlsx](https://github.com/jerryzuo0214/Integrated_Examation_Of_Ten_Subjects_WMU/files/5850625/-20210121.xlsx)
[

](url)
