### ISSUE TITLE
关于保存习题进度

### ISSUE THREAD

**Issue by rw996419** [jerryzuo0214/Integrated_Examination_Of_Ten_Subjects_WMU#25]
一个习题集进度保存后，再进入第二个习题集时，题目顺序仍然被保存为第一个习题集的进度。🤔

ex:药理学做到第五题后退出，打开系统解剖学，显示的是系统解剖学的第五题而并非第一题。其他习题集同理。

**Comment by jerryzuo0214** [comment]
您好，收到您的回复，这个问题将会很快解决，新版本将解决此问题噢，目前替代方案是做完题目后使用返回键直接返回，来规避此问题

**Comment by jerryzuo0214** [comment]
您好，排查代码后我们发现程序关于题目做题记忆模块存在问题，已火速修复，请关注最新版下载使用！感谢您的宝贵意见

**Comment by rw996419** [comment]
👍 👍
